accordion/urls.py
from django.urls import path
from . import views

app_name = 'accord'

urlpatterns = [
    path('', views.accord, name='homeaccord'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('<id>', views.change, name='color'),
    path('confirm/', views.formed, name='form'),
    path('confirm/<id>', views.novalid, name='formdelete'),
]

story10/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.loginpage, name='login'),
    path('register', views.register, name='register'),
    path('hello', views.message, name='message'),
    path('logout', views.logoutpage, name='logout')
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accord/',include('accordion.urls')),
    path('story9/',include('story9.urls')),
    path('story10/',include('story10.urls'))
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'ajx'

urlpatterns = [
    path('', views.landing, name='landing'),
]

accordion/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    nama = models.CharField(max_length = 30)
    pesan = models.CharField(max_length = 100)
    warna = models.CharField(max_length = 30, default = "black")

    def __str__(self):
        return self.nama

story10/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story10/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields= ['username', 'email', 'password1', 'password2']

accordion/views.py
from django.shortcuts import render, redirect

# Create your views here.
def accord(request):
    return render(request,"acc.html")

home/views.py
from django.shortcuts import render, redirect
from .models import Person
import random
# Create your views here.
def homepage(request):
    objek = Person.objects.all()
    return render(request,'home.html',{'isinya' : objek})

def formed(request):
    if request.method == "POST":
        name = request.POST['name']
        message = request.POST['pesan']
        new_obj = Person.objects.create(nama = name, pesan = message)
        new_obj.save()

        return render(request,'konfirmasi.html',{'obj':new_obj})

def novalid(request,id):
    ent = Person.objects.get(id=id)
    ent.delete()
    return redirect('/')

def change(request,id):
    color = ['red','green','blue','yellow']
    newcol = color[random.randint(0,3)]
    ent = Person.objects.get(id=id)
    ent.warna = newcol
    ent.save()
    return redirect('/')

story10/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def loginpage(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/story10/hello')

    return render(request,'login.html')

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/story10/')
    context = {'form' : form}
    return render(request,'register.html', context)

def message(request):
    if request.user.is_authenticated:
        return render(request,'hello.html')
    else:
        return redirect('/story10/')

def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/story10/')
    else:
        return redirect('www.google.com/login dulu pak')

story9/views.py
from django.shortcuts import render, redirect

# Create your views here.
def landing(request):
    return render(request,'book.html')

accordion/templates/acc.html
{% extends "base.html" %}
{% load static %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'accstyle.css' %}">
<script src="{% static 'styling.js' %}"></script>
{% endblock %}
{% block main_content %}
<!-- <iframe width="0" height="0" src="https://www.youtube.com/embed/HSOtku1j600?autoplay=1" frameborder="0" allow="autoplay;" allowfullscreen></iframe> -->
<div class="accordian">
    <h1 style="color: pink; cursor: pointer;" class="pinktext">これは私のアコーディオンです</h1>
    <div class="card" id="testedcard">
        <div class="card-header nezuko">
            <h3 class="carda">Get To Know Me</h3>
            <i class="fa fa-arrow-circle-up logox upper"  id="testedupper" style="font-size: 30px; color: white;"></i>
            <i class="fa fa-arrow-circle-down logox downer" id="testeddowner" style="font-size: 30px; right:50px; color: white;"></i>
        </div>
        <div class="card-body" >
            <p>
                Name : Nofaldi Fikrul Atmam <br>
                You can call me anytime (UwU) <br>
                i kinda like watching anime, nah just kidding i really like it.
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header nezuko">
            <h3 class="carda">What I Do Now</h3>
            <i class="fa fa-arrow-circle-up logox upper" style="font-size: 30px; color: white;"></i>
            <i class="fa fa-arrow-circle-down logox downer" style="font-size: 30px; right:50px; color: white;"></i>
        </div>
        <div class="card-body">
            <p>
                PJJ is fucking me up man <br>
                i only studying in my room right now <br>
                sometime i play games <br>
                but anime is lyfe <br>
                also doing my project
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header nezuko">
            <h3 class="carda">My Recent Organization</h3>
            <i class="fa fa-arrow-circle-up logox upper" style="font-size: 30px; color: white;"></i>
            <i class="fa fa-arrow-circle-down logox downer" style="font-size: 30px; right:50px; color: white;"></i>
        </div>
        <div class="card-body">
            <p>
                Right now im on faculty of computer science student executiv <br>
                i also apply PERAK and Compfest <br>
                i also part timing at my friends company as a backend developer 
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header nezuko">
            <h3 class="carda">Current Following Anime</h3>
            <i class="fa fa-arrow-circle-up logox upper" style="font-size: 30px; color: white;"></i>
            <i class="fa fa-arrow-circle-down logox downer" style="font-size: 30px; right:50px; color: white;"></i>
        </div>
        <div class="card-body">
            <p>
                One Piece <br>
                En En No Shoubotai <br>
                Black Clover <br>
                BNHA <br>
                TANJIRO MATI
            </p>
        </div>
    </div>
    <img src="/static/nezuko1.png"  class="nezuco" id="foto" style="width: 300px; height: 300px; margin-left: 120px; cursor: pointer;" alt="This Is Cute Nezuko">
</div>


{% endblock %}

home/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}
<div class="inputdata">
    <h1 class="text">please input your data</h1>
    <form action="/confirm/" method="POST">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Your name here" class="box" required>
        <input type="text" name="pesan" placeholder="your meesage here" class="box" required>
        <input type="submit" value="Submit" id="submit">
    </form>
</div>
<div class="konten">
    {% if isinya|length != 0 %}
    {% for x in isinya %}
    <div class="blurred-box" style="background:{{ x.warna }};">
        <div class="user-login-box">
          <span class="user-icon"></span>
          <div class="user-name">{{ x.nama }}</div>
          <div class="pesan">"{{ x.pesan }}"</div>
          <a href="{% url 'home:color' x.id %}" class="buttonx" name="colorchange" ><button>Change Color</button></a>
        </div>
      
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

home/templates/konfirmasi.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}
<div class="inputdatax">
    <h1 class="text">Is this data valid?</h1>
    <p class="text">Your Name : {{ obj.nama }}</p>
    <p class="text">Your Message : {{ obj.pesan }}</p>
    <div class="buttonx">
        <a href="{% url 'home:homepage' %}"><button id="yesclicker">Yes</button></a>
        <a href="{% url 'home:formdelete' obj.id %}"><button id="noclicker">No</button></a>
    </div>
</div>
{% endblock %}

story10/templates/hello.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Welcome Page</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/stylex.css' %}" />
</head>

<body>
	<a href="{% url 'authentication:logout' %}">LOGOUT</a>
	<h1>Welcome {{ request.user }}</h1>
	<h1>{{ request.user.first_name }}</h1>
	<h1>{{ request.user.last_name }}</h1>
	<!-- <div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h3>Welcome To The Club</h3>
				<h1><span>{{ request.user.first_name }}</span></h1>
			</div>
			<h2>Hope You Enjoy</h2>
		</div>
    </div> -->

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

story10/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Register Your Account</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<img class="wave" src="{% static 'img/wave.svg' %}">
	<div class="container">
		<div class="img">
			<img src="{% static 'img/celeb.svg' %}">
		</div>
		<div class="login-content">
			<form action="" method="POST">
                {% csrf_token %}
				<img src="{% static 'img/avatar.svg' %}">
				<h2 class="title">Log In</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" name="username">
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-envelope"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" name="password">
            	   </div>
            	</div>
                {{ form.errors }}
                <a href="{% url 'authentication:register' %}" id="signup">Sign Up Now</a>
            	<input type="submit" class="btn" value="Log In" id="login">
            </form>
        </div>
    </div>
</body>
</html>

story10/templates/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Register Your Account</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<img class="wave" src="{% static 'img/wave.svg' %}">
	<div class="container">
		<div class="img">
			<img src="{% static 'img/bg.svg' %}">
		</div>
		<div class="login-content">
			<form action="" method="POST">
                {% csrf_token %}
				<img src="{% static 'img/avatar.svg' %}">
				<h2 class="title">Register</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		{{ form.username }}
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-envelope"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Email</h5>
           		    	{{ form.email }}
            	   </div>
            	</div>
            	<div class="input-div pass">
                    <div class="i"> 
                         <i class="fas fa-lock"></i>
                    </div>
                    <div class="div">
                        <h5>Password</h5>
                        {{ form.password1 }}
                    </div>
                </div>
                <div class="input-div pass">
                    <div class="i"> 
                         <i class="fas fa-lock"></i>
                    </div>
                    <div class="div">
                        <h5>Confirm Your Password</h5>
                        {{ form.password2 }}
                    </div>
                </div>
                {{ form.errors }}
                <a href="{% url 'authentication:login' %}" id="signin">Already have an account?</a>
            	<input type="submit" class="btn" value="Sign Up">
            </form>
        </div>
    </div>
</body>
</html>

story9/templates/book.html
{% extends "base.html" %}
{% load static %}
{% block title%}
Story9-PPW
{% endblock %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'styleajx.css' %}">
<script src="{% static 'ajx.js' %}"></script>
{% endblock %}
{% block main_content %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Book Search</a>
        </div>
        <div class="form-inline formex">
            <input class="form-control mr-sm-2" type="text" id="valued" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 inputted" id="inputted">Search</button>
        </div>
    </div>
</nav>
<div class="container">
    <table class="table table-hover tbl" id="tblanswr">
        <thead>
            <tr>
                <th>Title</th>
                <th>Publisher</th>
                <th>Author</th>
                <th>
                    <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#exampleModalCentered" id="modale">
                        Show Top 5
                    </button>

                    <!-- Modal -->
                    <div class="modal" id="exampleModalCentered" tabindex="-1" role="dialog"
                        aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalCenteredLabel">Top 5 Most Like Books</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                                </div>
                                <div class="modal-body isibody">
                                    ...
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody class="answr">
        </tbody>
    </table>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'static.css' %}">
    <title>{% block title %}Story7-PPW{% endblock %}</title>
    {% block additional_css %}{% endblock %}
</head>
<body class="bg">
    {% block main_content %}
    {% endblock %}
</body>
</html>